apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: false
    jsonData:
      version: Flux
      organization: falconeye
      defaultBucket: mybucket
    secureJsonData:
      token: supersecrettoken
